# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  # Root package.json
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
      # Use Eastern Standard Time (UTC -05:00)
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
      - 'area: UI'

  # Wallet Web package.json
  - package-ecosystem: 'npm'
    directory: '/cmd/wallet-web'
    schedule:
      interval: 'weekly'
      day: 'monday'
      # By default, the time is set to 05:00
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
      - 'area: UI'

  # UI Automation package.json
  - package-ecosystem: 'npm'
    directory: '/test/ui-automation'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '04:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
      - 'area: integration tests'

  # Demo Login Consent Server go.mod
  - package-ecosystem: 'gomod'
    directory: '/test/mock/demo-login-consent-server'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
      - 'area: backend'

  # Wallet Web Dockerfile
  - package-ecosystem: 'docker'
    directory: '/images/wallet-web'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '04:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
      - 'area: docker'

  # Demo Login Consent Server Dockerfile
  - package-ecosystem: 'docker'
    directory: '/test/mock/demo-login-consent-server/image'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '06:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
      - 'area: docker'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'friday'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
      - 'area: CI/CD'
